name: Go
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go_version: [1.11.13, 1.12.8, 1.13beta1]

    name: Build (Go ${{ matrix.go_version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        id: go
        with:
          version: ${{ matrix.go_version }}
      - uses: actions/checkout@master
      - name: go-mod-download
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: run-linter
        uses: docker://golangci/golangci-lint
        with:
          entrypoint: golangci-lint
          args: run --enable-all -D lll -D errcheck

      - name: run-tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -count 20
