name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "3 1 * * 3"
jobs:
  build:
    strategy:
      matrix:
        go_version:
          - 1.12.x
          - 1.13.x

    name: Build (Go ${{ matrix.go_version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1.0.2
        id: go
        with:
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@v1.0.0

      - run: go version

      - name: go-mod-download
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: run-linter
        uses: docker://golangci/golangci-lint
        env:
          GOROOT: /usr/local/go
        with:
          entrypoint: golangci-lint
          args: run --enable-all -D lll -D errcheck

      - name: run-tests
        run: go test -mod readonly -race -coverprofile=coverage.txt -covermode=atomic -count 20
