name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "3 1 * * 3"
jobs:
  build:
    strategy:
      matrix:
        go_version:
          - 1.14
          - 1.15
        os:
          - macos
          - ubuntu

    name: Build (${{ matrix.os }}/go-${{ matrix.go_version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          stable: false
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@v2.3.3

      - name: run-tests
        run: go test -mod readonly -race -coverprofile=coverage.txt -covermode=atomic -count 20

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - uses: golangci/golangci-lint-action@v2.3.0
